# Generated by Django 5.2.15 on 2026-06-10 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='ชื่อกลุ่ม')),
                ('color', models.CharField(default='#FF4B4B', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'กลุ่มแท็ก',
                'verbose_name_plural': 'กลุ่มแท็ก',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FixCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ปี (ค.ศ.)')),
                ('month', models.PositiveSmallIntegerField(verbose_name='เดือน')),
                ('label', models.CharField(max_length=255, verbose_name='รายการ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='จำนวนเงิน')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ค่าใช้จ่ายคงที่',
                'verbose_name_plural': 'ค่าใช้จ่ายคงที่',
                'ordering': ['-year', '-month', 'label'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'label'), name='uniq_fixcost_period_label')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ชื่อแท็ก')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalog.taggroup')),
            ],
            options={
                'verbose_name': 'แท็ก',
                'verbose_name_plural': 'แท็ก',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('LIVE', 'ร้านค้าจริง'), ('TEST', 'สินค้าทดสอบ')], default='LIVE', max_length=4)),
                ('sku', models.CharField(db_index=True, max_length=255, verbose_name='SKU')),
                ('name', models.TextField(blank=True, default='', verbose_name='ชื่อสินค้า')),
                ('type', models.CharField(blank=True, default='กลุ่ม ปกติ', max_length=100, verbose_name='หมวดหมู่')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุน')),
                ('box_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคากล่อง')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าส่งเฉลี่ย')),
                ('com_admin_pct', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='คอม Admin (%)')),
                ('com_tele_pct', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='คอม Telesale (%)')),
                ('p_jnt', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='J&T (%)')),
                ('p_flash', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Flash (%)')),
                ('p_kerry', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Kerry (%)')),
                ('p_thai_post', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='ThailandPost (%)')),
                ('p_dhl', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='DHL (%)')),
                ('p_spx', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='SPX (%)')),
                ('p_lex', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='LEX (%)')),
                ('p_std', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Standard (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สินค้า (Master)',
                'verbose_name_plural': 'สินค้า (Master)',
                'constraints': [models.UniqueConstraint(fields=('channel', 'sku'), name='uniq_masteritem_channel_sku')],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('LIVE', 'ร้านค้าจริง'), ('TEST', 'สินค้าทดสอบ')], default='LIVE', max_length=4)),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='catalog.tag')),
            ],
            options={
                'verbose_name': 'แท็กสินค้า',
                'verbose_name_plural': 'แท็กสินค้า',
                'constraints': [models.UniqueConstraint(fields=('channel', 'sku', 'tag'), name='uniq_producttag')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_tag_group_name'),
        ),
    ]
