# Generated by Django 5.2.15 on 2026-06-10 07:37

import apps.ingest.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อร้าน')),
                ('channel', models.CharField(choices=[('LIVE', 'ร้านค้าจริง'), ('TEST', 'สินค้าทดสอบ')], default='LIVE', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ร้านค้า',
                'verbose_name_plural': 'ร้านค้า',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'name'), name='uniq_shop_channel_name')],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SALES', 'ไฟล์ยอดขาย'), ('ADS', 'ไฟล์โฆษณา')], max_length=8)),
                ('file', models.FileField(upload_to=apps.ingest.models.upload_path)),
                ('original_name', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'กำลังประมวลผล'), ('PROCESSED', 'นำเข้าแล้ว'), ('ERROR', 'ล้มเหลว')], default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('row_count', models.IntegerField(default=0)),
                ('date_min', models.DateField(blank=True, null=True)),
                ('date_max', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ingest.shop')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ไฟล์นำเข้า',
                'verbose_name_plural': 'ไฟล์นำเข้า',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('LIVE', 'ร้านค้าจริง'), ('TEST', 'สินค้าทดสอบ')], db_index=True, max_length=4)),
                ('order_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('courier_raw', models.CharField(blank=True, default='', max_length=255)),
                ('courier_norm', models.CharField(blank=True, default='', max_length=255)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('sku_raw', models.CharField(blank=True, default='', max_length=255)),
                ('sku_norm', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sku_root', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creator', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='', max_length=255)),
                ('work_type', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.TextField(blank=True, default='')),
                ('role', models.CharField(default='Unknown', max_length=10)),
                ('is_cod', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lines', to='ingest.shop')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lines', to='ingest.uploadedfile')),
            ],
            options={
                'verbose_name': 'รายการขาย',
                'verbose_name_plural': 'รายการขาย',
            },
        ),
        migrations.CreateModel(
            name='AdSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('LIVE', 'ร้านค้าจริง'), ('TEST', 'สินค้าทดสอบ')], db_index=True, max_length=4)),
                ('date', models.DateField(db_index=True)),
                ('campaign_name', models.TextField(blank=True, default='')),
                ('sku_root', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_rows', to='ingest.shop')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_rows', to='ingest.uploadedfile')),
            ],
            options={
                'verbose_name': 'ค่าโฆษณา',
                'verbose_name_plural': 'ค่าโฆษณา',
            },
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(fields=('shop', 'kind', 'sha256'), name='uniq_file_shop_kind_sha'),
        ),
        migrations.AddIndex(
            model_name='salesline',
            index=models.Index(fields=['channel', 'date'], name='ingest_sale_channel_10d5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesline',
            index=models.Index(fields=['channel', 'sku_root'], name='ingest_sale_channel_880c70_idx'),
        ),
        migrations.AddIndex(
            model_name='adspend',
            index=models.Index(fields=['channel', 'date'], name='ingest_adsp_channel_8fb8d5_idx'),
        ),
    ]
