# Generated by Django 5.2.15 on 2026-09-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_fact_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อพนักงาน')),
                ('team', models.CharField(blank=True, default='', max_length=100, verbose_name='ทีม')),
                ('salary_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เงินเดือน/วัน')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'พนักงาน Telesale',
                'verbose_name_plural': 'พนักงาน Telesale',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_creator', models.CharField(max_length=255, unique=True, verbose_name='ชื่อผู้สร้างออเดอร์ (ตามไฟล์)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analytics.employee')),
            ],
            options={
                'verbose_name': 'ชื่อผู้สร้างออเดอร์ (Alias)',
                'verbose_name_plural': 'ชื่อผู้สร้างออเดอร์ (Alias)',
                'ordering': ['raw_creator'],
            },
        ),
    ]
